#!/usr/bin/env python
# coding: utf-8

# # 3. Molecular surface analysis
# 
# Data describing the solvent-accessible surface of a molecule is of great utility in the
# development of that molecule as a therapeutic, particularly in the case of antibodies. In the
# context of this report, the most obvious application of molecular surface data is in combination
# with the potential sites of chemical modification, described in the previous section. Antibodies
# (and other proteins) are known to undergo many different chemical modifications as a result of
# interactions with their aqueous environment. The probability and kinetic rate of such a
# modification is greatly enhanced by the degree of exposure of the potential modification site to
# the solvent environment.
# If a 3D structure was supplied or requested by the client, then the graphs below will show the
# solvent-accessible surface areas in (Å2) calculated for each residue in the light and heavy chain
# variable regions of the antibody. These solvent-accessible surfaces are calculated using the
# “rolling ball” algorithm developed by Shrake & Rupley in which a spherical solvent “probe” is3
# used, the accessible surface being generated by tracing the center of the probe sphere as it
# rolls along the van der Waals surface (as shown below).
# 
# ![](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Accessible_surface.svg/280px-Accessible_surface.svg.png)
# 
# <p align="center">
#     Image by Keith Callenberg - courtesy of Wikimedia Common
# </p>
# 
# The solvent-accessible surface for each residue depends upon the degree of exposure of the
# residue on the antibody surface, but also on the size of the residue side chain. Residues that
# are completely buried within the hydrophobic core of the antibody, will have solvent-accessible
# surface areas at or close to zero. Residues that are highly exposed at the antibody surface will
# have values that range from around 100 - 200 Å2, depending upon the size of the residue side
# chain and the degree of exposure.
# 
# ## solvent-accessible surface plot 
# 

# In[ ]:




